/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthSettingsUsersRouteImport } from './routes/_auth/settings/users'
import { Route as AuthSettingsPermissionsIndexRouteImport } from './routes/_auth/settings/permissions.index'
import { Route as AuthSettingsPermissionsRoleIdRouteImport } from './routes/_auth/settings/permissions.$roleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsUsersRoute = AuthSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsPermissionsIndexRoute =
  AuthSettingsPermissionsIndexRouteImport.update({
    id: '/settings/permissions/',
    path: '/settings/permissions/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsPermissionsRoleIdRoute =
  AuthSettingsPermissionsRoleIdRouteImport.update({
    id: '/settings/permissions/$roleId',
    path: '/settings/permissions/$roleId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/settings/users': typeof AuthSettingsUsersRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/settings/permissions/$roleId': typeof AuthSettingsPermissionsRoleIdRoute
  '/settings/permissions/': typeof AuthSettingsPermissionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/settings/users': typeof AuthSettingsUsersRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/settings/permissions/$roleId': typeof AuthSettingsPermissionsRoleIdRoute
  '/settings/permissions': typeof AuthSettingsPermissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/settings/users': typeof AuthSettingsUsersRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/settings/permissions/$roleId': typeof AuthSettingsPermissionsRoleIdRoute
  '/_auth/settings/permissions/': typeof AuthSettingsPermissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings/users'
    | '/settings/'
    | '/settings/permissions/$roleId'
    | '/settings/permissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/settings/users'
    | '/settings'
    | '/settings/permissions/$roleId'
    | '/settings/permissions'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/'
    | '/_auth/settings/users'
    | '/_auth/settings/'
    | '/_auth/settings/permissions/$roleId'
    | '/_auth/settings/permissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/users': {
      id: '/_auth/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthSettingsUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/permissions/': {
      id: '/_auth/settings/permissions/'
      path: '/settings/permissions'
      fullPath: '/settings/permissions/'
      preLoaderRoute: typeof AuthSettingsPermissionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/permissions/$roleId': {
      id: '/_auth/settings/permissions/$roleId'
      path: '/settings/permissions/$roleId'
      fullPath: '/settings/permissions/$roleId'
      preLoaderRoute: typeof AuthSettingsPermissionsRoleIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSettingsUsersRoute: typeof AuthSettingsUsersRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthSettingsPermissionsRoleIdRoute: typeof AuthSettingsPermissionsRoleIdRoute
  AuthSettingsPermissionsIndexRoute: typeof AuthSettingsPermissionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthSettingsUsersRoute: AuthSettingsUsersRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthSettingsPermissionsRoleIdRoute: AuthSettingsPermissionsRoleIdRoute,
  AuthSettingsPermissionsIndexRoute: AuthSettingsPermissionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
