export const Error = {
  INVALID_ADDRESS_EMAIL: "INVALID_ADDRESS_EMAIL",
  REQUIRED_FIELD: "REQUIRED_FIELD",
  MIN_LENGTH: (num: number) => `MIN_LENGTH_${num.toString()}` as const,
  REQUIRED_LOWERCASE: "REQUIRED_LOWERCASE",
  REQUIRED_UPPERCASE: "REQUIRED_UPPERCASE",
  REQUIRED_DIGIT: "REQUIRED_DIGIT",
  REQUIRED_SPECIAL: "REQUIRED_SPECIAL",
} as const;
